from django.conf.urls import patterns, include, url
from website.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'heilujiao.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', welcome),
    url(r'^$', index),
    url(r'^about/$', about),
    url(r'^address/$', address),
    url(r'^blog/$', blog),
    url(r'^cart/$', cart),
    url(r'^detail/$', detail),
    url(r'^menu/$', menu),
    url(r'^menu/main/$', menuMain),
    url(r'^menu/salad/$', menuSalad),
    url(r'^menu/deal/$', menuDeal),
    url(r'^menu/month/$', menuMonth),
    url(r'^menu/popular/$', menuPopular),
    url(r'^submit/$', submit),
    url(r'^detail/(\d+)/$', detail),
    url(r'^register/$', register),
    url(r'^login/$', login),
    url(r'^logout/$', logout),
    url(r'^forgetpwd/$', forgetpwd),
    url(r'^add/$', add),
    url(r'^addDeal/$', addDeal),
    url(r'^changeDeal/$', changeDeal),
    url(r'^upload/$', upload),
    url(r'^saveAddress/$', saveAddress),
    url(r'^deleteAddress/$', deleteAddress),
    url(r'^changeAddressSave/$', changeAddressSave),
    url(r'^changeAddress/(\d+)/$', changeAddress),
    url(r'^root/$', root),
    url(r'^uploadPage/$', uploadPage),
    url(r'^indexUpdate/$', indexUpdate),
    url(r'^blogUpdate/$', blogUpdate),
    url(r'^slideAdd/$', slideAdd),
    url(r'^blogAdd/$', blogAdd),
    url(r'^blogChange/$', blogChange),
    url(r'^checkMenu/$', checkMenu),
    url(r'^changeMenu/(\d+)/$', checkMenuDetail),
    url(r'^changeBlog/(\d+)/$', checkBlogDetail),
    url(r'^checkBlog/$', checkBlog),
    url(r'^confirmDelete/$', confirmDelete),
    url(r'^confirmDeleteBlog/$', confirmDeleteBlog),
    url(r'^setCapcha/$', setCapcha),
    url(r'^pay/$', pay),
    url(r'^addCoupon/$', addCoupon),
    url(r'^addCouponValidate/$', addCouponValidate),
    url(r'^checkCoupon/$', checkCoupon),
    url(r'^confirmDeleteCoupon/$', confirmDeleteCoupon),
    url(r'^validateCoupon/$', validateCoupon),
    url(r'^cancelCoupon/$', cancelCoupon),
    url(r'^checkUser/$', checkUser),
    url(r'^checkOrder/$', checkOrder),
    url(r'^payment/$', payment),
    url(r'^alipayReturn/$', alipayReturn),
    url(r'^alipayNotify/$', alipayNotify),
    url(r'^checkTip/$', checkTip),
    url(r'^validateTip/$', validateTip),
)