from django.contrib import admin
from edco.models import *

admin.site.register(Product)
admin.site.register(Comment)
admin.site.register(User)
admin.site.register(Color)
admin.site.register(Tech)
admin.site.register(Slide)
admin.site.register(Indexproduct)
admin.site.register(Recomment)
admin.site.register(Promotion)
admin.site.register(Out)
admin.site.register(Gift)
admin.site.register(project1)
admin.site.register(project2)
admin.site.register(Subangdai)
admin.site.register(Hyundai1)
admin.site.register(Hyundai2)
admin.site.register(Hyundai3)
admin.site.register(Hyundai4)
admin.site.register(Hyundai5)
admin.site.register(Hyundai6)
admin.site.register(Hyundai7)
admin.site.register(Hyundai8)
admin.site.register(Hyundai9)
admin.site.register(Hyundai10)
