<?php
$data = array (
  0 => 
  array (
    'cat_id' => '9',
    'cat_name' => '咨询热点',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '5',
    'cat_name' => '最新消息',
    'cat_type' => '1',
    'keywords' => '檀香最新动态，檀香新闻',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '3',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '4',
    'cat_name' => '品牌故事',
    'cat_type' => '1',
    'keywords' => '檀香简介，植物形态，檀香文化',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  4 => 
  array (
    'cat_id' => '6',
    'cat_name' => '香道文化',
    'cat_type' => '1',
    'keywords' => '香道文化，产地，品种',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  5 => 
  array (
    'cat_id' => '7',
    'cat_name' => '关于我们',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  6 => 
  array (
    'cat_id' => '8',
    'cat_name' => '媒体报道',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  7 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '7',
  ),
  8 => 
  array (
    'cat_id' => '3',
    'cat_name' => '网店帮助分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  9 => 
  array (
    'cat_id' => '10',
    'cat_name' => '最新资讯',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '5',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  10 => 
  array (
    'cat_id' => '11',
    'cat_name' => '新闻动态',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '5',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  11 => 
  array (
    'cat_id' => '12',
    'cat_name' => '优惠活动',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '5',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
);
?>