<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '极品香系列',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 0,
    'id' => '1',
    'name' => '极品香系列',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '香道用具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 0,
    'id' => '4',
    'name' => '香道用具',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '日常用香',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 0,
    'id' => '3',
    'name' => '日常用香',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '高级香系列',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 0,
    'id' => '2',
    'name' => '高级香系列',
  ),
);
?>